server:
  port: 9091
  
#JDBC Oracle Connection
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: scott
    password: tiger

# MyBatis
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  type-aliases-package: com.myturn.model.vo
  type-handlers-package: com.myturn.model.dao